baseurl = "https://kairos-stellar.pages.dev/"
languageCode = "fr-fr"
title = "Kairos — Gestion d'agence pour architectes"
theme = "stellar"

[params]
  company = "Atelier Oni"
  [params.header]
    title = "Kairos"
    subtitle = "L'outil qui simplifie ta gestion et ta journée d'architecte"
  
  [params.footer]
    title = "Aliquam sed mauris"
    description = "Sed lorem ipsum dolor sit amet et nullam consequat feugiat..."
    link = "#"
  
  [params.contact]
    email = "contact@kairos-app.website"
  
  [[params.social]]
    name = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com"
  
  [[params.social]]
    name = "GitHub"
    icon = "fa-github"
    link = "https://github.com"

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Features"
  url = "#features"
  weight = 2

[[menu.main]]
  name = "Télécharger"
  url = "/download/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
